ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "productType" TEXT NOT NULL DEFAULT 'service',
ADD COLUMN IF NOT EXISTS "serviceMode" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "serviceDuration" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "appointmentRequired" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "specText" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "deliveryText" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "afterSaleText" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "stockStatus" TEXT NOT NULL DEFAULT 'available';

CREATE INDEX IF NOT EXISTS "Product_productType_status_idx" ON "Product"("productType", "status");
